---
name: Unix-Uptime
version: 0.3
author:
  - 'Mike Kelly <pioto@pioto.org>'
abstract: |-
  Determine the current uptime, in seconds, across
  different *NIX architectures
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://git.pioto.org/gitweb/Unix-Uptime.git
build_requires:
  Module::Build: 0.28
provides:
  Unix::Uptime:
    file: lib/Unix/Uptime.pm
    version: 0.3
  Unix::Uptime::BSD:
    file: lib/Unix/Uptime/BSD.pm
  Unix::Uptime::FreeBSD:
    file: lib/Unix/Uptime/FreeBSD.pm
  Unix::Uptime::Linux:
    file: lib/Unix/Uptime/Linux.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
