---
name: Unix-Uptime
version: 0.37
author:
  - 'Mike Kelly <pioto@pioto.org>'
abstract: |-
  Determine the current uptime, in seconds, and load
  averages, across different *NIX architectures
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Unix-Uptime
  license: http://dev.perl.org/licenses/
  repository: http://git.pioto.org/gitweb/Unix-Uptime.git
configure_requires:
  Module::Build: 0.28
build_requires:
  Module::Build: 0.28
provides:
  Unix::Uptime:
    file: lib/Unix/Uptime.pm
    version: 0.37
  Unix::Uptime::BSD:
    file: lib/Unix/Uptime/BSD.pm
    version: 0.37
  Unix::Uptime::BSD::XS:
    file: lib/Unix/Uptime/BSD/XS.pm
    version: 0.37
  Unix::Uptime::Linux:
    file: lib/Unix/Uptime/Linux.pm
    version: 0.37
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
